name: pokedex
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: 6.2.1
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  auto_route: ^9.2.1+1
  flutter_svg: 2.0.10+1
  logger: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  collection: ^1.18.0
  gap: 3.0.1
  shimmer: 3.0.0
  http: ^1.1.0
  shared_preferences: 2.2.3
  flutter_slidable: 3.1.1
  flutter_riverpod: ^2.5.1

  self_utils:
    path: ../../packages/self_utils

  window_manager_service:
    path: ../../services/window_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ">=2.3.0 <4.0.0"
  flutter_gen_runner:
  auto_route_generator: ^9.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/